### ISSUE TITLE
Integration for Europe

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#13]
1. merchant IDs (MIDs) - for Europe, depending on how a merchant's store is legally set up, Klarna could use either a single MID across all their European stores or a separate MID for each European country.  The Woo admin settings need to be able to handle either option.  
2. default Title & default Description - still a pending legal question (for UK) regarding this, but for now, we will proceed to offer these as configurable by the merchant (but we should default them.  For US, default should be Title="Pay Over Time" and Description="Get the flexibility to pay over time with Klarna!")
3.  link for "What is Klarna?" - For US default to "https://www.klarna.com/us/pay-over-time", for Europe, use https://www.klarna.com/uk/what-we-do
4. Customer locales - Woo plugin pulls the customer's locale from the customer's browser.  If locale is offered by Klarna, it is used, but if not, locale will be defaulted to appropriate locale.   Since the locale sent with the order is the merchant's locale, is the customer locale used?
5. discounts - until we get different feedback, we can leave discount logic as is (discount is listed on the order line items, and also a $0 discount is logged as its own order line item).
6. taxes/VAT - match logic for how taxes/VAT are implemented for KCO, for Europe this should mean VAT is always listed on the line item level
7. For non-US, due to data secrecy legal requirements, do not send customer data on KlarnaCredit.load JS call. 
8. Will need config for selection of countries for which KP is available for.

**Comment by slobodan** [comment]
Converting your comment to task list.

- [ ] merchant IDs (MIDs) - for Europe, depending on how a merchant's store is legally set up, Klarna could use either a single MID across all their European stores or a separate MID for each European country. The Woo admin settings need to be able to handle either option.
- [ ] default Title & default Description - still a pending legal question (for UK) regarding this, but for now, we will proceed to offer these as configurable by the merchant (but we should default them. For US, default should be Title="Pay Over Time" and Description="Get the flexibility to pay over time with Klarna!")
- [ ] link for "What is Klarna?" - For US default to "https://www.klarna.com/us/pay-over-time", for Europe, use https://www.klarna.com/uk/what-we-do
- [ ] Customer locales - Woo plugin pulls the customer's locale from the customer's browser. If locale is offered by Klarna, it is used, but if not, locale will be defaulted to appropriate locale. Since the locale sent with the order is the merchant's locale, is the customer locale used?
- [ ] discounts - until we get different feedback, we can leave discount logic as is (discount is listed on the order line items, and also a $0 discount is logged as its own order line item).
- [ ] taxes/VAT - match logic for how taxes/VAT are implemented for KCO, for Europe this should mean VAT is always listed on the line item level
- [ ] For non-US, due to data secrecy legal requirements, do not send customer data on KlarnaCredit.load JS call.
- [ ] Will need config for selection of countries for which KP is available for.

**Comment by slobodan** [comment]
@kristibarbosky what should title and description defaults be for EU?

**Comment by slobodan** [comment]
Currency switcher plugin - Aelia Currency Switcher

**Comment by kristibarbosky** [comment]
Please change the tab for Klarna Payments config settings in Woo Admin to be titled "Klarna Payments".  ("Pay Over Time" is a US product available via the Klarna Payments API.)

**Comment by johannesclaudi** [comment]
@kristibarbosky Regarding: link for "What is Klarna?" - For US default to "https://www.klarna.com/us/pay-over-time", for Europe, use https://www.klarna.com/uk/what-we-do
for Europe this should rather be https://www.klarna.com. Based on the geolocation the customer then gets redirected to e.g. https://www.klarna.com/de or https://www.klarna.com/uk.

**Comment by kristibarbosky** [comment]
In one store,

**Comment by slobodan** [comment]
Fixed tab title (from Pay Over Time to Klarna Payments)

**Comment by slobodan** [comment]
@kristibarbosky 

Just tried this:

> For a DE store, checking out with an NL address, I'm getting an iframe in English (on https://wp-kp.mageklarna.com). Since create_session will use store data (since customer data isn't yet entered), authorize will need to update these fields accordingly. I suspect the iframe is returning in English when there is a mismatch in locale/purchase_country, purchase_currency.

And I get the NL iframe:

![screen shot 2017-06-07 at 13 17 14](https://user-images.githubusercontent.com/129607/26875791-b265498c-4b83-11e7-974a-3109668e5cf6.png)

Store base is set to DE, incognito window. Am I doing wrong wrong? Which fields needed to be updated on authorize?

**Comment by slobodan** [comment]
No PII in non-US.

**Comment by slobodan** [comment]
Shared secret encoding.

**Comment by slobodan** [comment]
Fixed no PII in EU countries, merging the branch into develop

**Comment by kristibarbosky** [comment]
Per testing:
- [ ] Only add the $0 discount data for US orders

**Comment by slobodan** [comment]
> #120.1 - Now that the plugin can use credentials across different countries (based on the customer's address data), order management must also pull the appropriate credentials for each order. Currently delete order is failing due to password mismatch. Also confirm, that the same password encoding/decoding is done in OM plugin now as is done in KP per #37 

I just did a test, base country = US, purchase country = SE (so credentials would be different) and everything went well.

On purchase, Klarna Payments plugin stores "Klarna purchase country" as order meta field, then Order Management plugin reads from this field so it can get proper credentials and API URLs.

Just added character decoding function to OM.

**Comment by slobodan** [comment]
User agent reference link - https://github.com/WordPress/WordPress/blob/332884f8dc30ef38ac6f0ad20af160b43c3cfc1a/wp-includes/class-http.php#L184

**Comment by slobodan** [comment]
> #40.9 - iframe runs off the screen on iphone4, is there any option to adjust spacing, to keep with Klarna's recommendation of 280px?

@kristibarbosky We don't control this, and it's different for every theme. Should we drop it?

**Comment by slobodan** [comment]
> some invalid phone numbers (e.g. "01515151515abbbb") allow the order to be placed, but then return a red Woo error, then after fixing the invalid phone number, iframe says No offers available, but after trying to place order twice, the order is placed in Klarna

This was tricky, but I think I found an acceptable solution. If order is being placed in WooCommerce and Klarna Payments is the selected payment method, billing phone number is filtered to remove any characters that would not pass WC phone validation (mostly, this means removing letters). 

This could mean mismatch in phone number as it is stored in Klarna and WooCommerce, but the one in Klarna is actually the wrong one (since it allows letters). A way to fix this is to also filter the phone number before it's sent to Klarna, but I think this is something that needs to be fixed on Klarna's end, since phone numbers should not contain letters anyway.

**Comment by slobodan** [comment]
Updated user agent to this format:

* WordPress/4.8; http://krokedil.klarna.ngrok.io - KP:1.0
* WordPress/4.8; http://krokedil.klarna.ngrok.io - OM:1.0

KP = Klarna Payments, OM = Order Management

**Comment by slobodan** [comment]
Refund information in docs: http://docs.krokedil.com/documentation/klarna-payments-woocommerce/klarna-order-management/#7

**Comment by kristibarbosky** [comment]
-[ ] When using autofill to fill in address form data, and then adding letters to the phone number, the first time I click the place order button, nothing happens on the page.  The order is successfully submitted on the 2nd time I click the place order button.  (Without autofill, instead typing in address data manually, the order is placed successfully on the first click of the place order button.)

**Comment by kristibarbosky** [comment]
- [ ] Even though the Klarna Payments plugin is correctly installed and enabled, it is not showing as Enabled in the Checkout settings under the Payment gateways settings:

![image](https://user-images.githubusercontent.com/15654455/28215365-c179a32c-687b-11e7-9f7e-e98cc9f17a3c.png)

![image](https://user-images.githubusercontent.com/15654455/28215376-ce695460-687b-11e7-97a3-ea567bb8ed24.png)

**Comment by kristibarbosky** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/15654455/28317177-e160e856-6b93-11e7-8469-454afaa3a68c.png)

**Comment by kristibarbosky** [comment]
Per discussion on Aug 22, 2017, closing this ticket as any other items needed for EU KP are covered under separate tickets.
