### ISSUE TITLE
Smart Coupons Gift Cards cause 400 Errors and go to a 404 Page

### ISSUE THREAD

**Issue by broksonic21** [krokedil/klarna-payments-for-woocommerce#204]
We ran into this https://github.com/krokedil/klarna-payments-for-woocommerce/issues/194

On a environment with just:
* WooCommerce
* WooCommerce Smart Coupons
* WooCommerce Klarna Payments for WooCommerce

If you use a gift card (of less than the full amount) and Klarna, it always errors with a 400 from Klarna due to order_amount.

This is another case where the error handling is off though - it takes you to a 404 page like this:
https://YOURSERVER/checkout/Klarna%20Payments%20API%20Error:%20400%20Bad%20Request%20%20Bad%20value:%20order_amount

Ideally both issues are addressed.

**Comment by kristibarbosky** [comment]
Per discussion with Krokedil & Klarna, unfortunately gift cards with Smart Coupons are not supported yet, as now documented per: https://docs.krokedil.com/article/382-klarna-payments-known-compatibility-issues#h-H2_1
This will be supported in the future though. 

We will look into displaying the error message in a better way (rather than the 404 page) though.

**Comment by MichaelBengtsson** [comment]
@broksonic21 The issue of redirecting to a 404 page with the error message has been located and fixed, and will be included in the next release. We will also look into adding support for the smart coupons issue before the next release.

**Comment by broksonic21** [comment]
Thanks.
