### ISSUE TITLE
Enable tracking of plugin installs & uninstalls

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#25]
Is there currently a way to track what stores have these plugins (both KP & OM) installed-activated, installed-deactivated, and uninstalled?

We would like to have this ability to track this.  Even just sending an email could work if that is the best approached.

**Comment by slobodan** [comment]
Currently, no.

This is from WordPress plugin guidelines (https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/):

> 7. The plugin may not “phone home” or track users without their informed, explicit, opt-in consent.

Also in that section:

> The sole exception to this policy is Software as a Service, such as Twitter, an Amazon CDN plugin, or Akismet. By installing, activating, registering, and configuring plugins that utilize those services, consent is granted for those systems.

Technically, if Klarna informs their WooCommerce merchants about tracking data before they even install the plugin, we should be fine, right? Doing this as opt-in would do no good, because data would not be complete in this case.

We can track activation, deactivation and uninstallation if done from Plugins page, but not when plugin is uploaded or deleted via FTP, probably not even when plugin zip file is uploaded via WordPress admin (it's still not active at that point, so none of its code will be executed).

Presuming we'll start with email, can you send me list of everything that needs to be sent, and where to send it.

**Comment by kristibarbosky** [comment]
Let's discuss further next status meeting.  This did come up as we thought through the scenario of the merchant have only the KP plugin installed/activated and not the OM plugin.  Merchants don't receive any errors, but this is not a desired installation.

**Comment by kristibarbosky** [comment]
Closed this ticket and opening a new ticket to put a notice on Woo admin if the store has KP plugin but not  OM plugin.  If it becomes a bigger issue, we can reopen this ticket if necessary.
