### ISSUE TITLE
Updates after code review

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#35]
Per discussion on March 16th, please update/review:

KP plugin:

1. Revise code so that it works outside of US too; do not hard code US anywhere
along with this, the authorize doesn't need purchase_currency or locale so these settings can be removed

2. for US, there should be no tax amount/rate on discounts, e.g. it should look like:

    {
      "reference": "discount",
      "type": "discount",
      "quantity": 1,
      "quantity_unit": "",
      "name": "Discount (5BUCKSOFF)",
      "total_amount": -500,
      "unit_price": -500,
      "total_discount_amount": 0,
      "tax_rate": 0,
      "total_tax_amount": 0,
      "merchant_data": null,
      "product_url": null,
      "image_url": null
    },

3. remove PayPal class for "What is Klarna?" link; instead just use inline CSS

4. purchase_country on order attribute - should be pulled from store info, not customer info

5. clean up of create_request_url

6. use a method if necessary, and use consistent way of calculating numbers, e.g. sometimes it wa number_format then round, other times 

multiply by 100 then round (applies to both KP & OM plugins)

7. if no shipping method is set, can the order still be placed?   Slobodan to check. 

OM plugin:

8. with the notification url, for stop requests - don't cancel orders, instead send email to merchant (if possible) and put not on order 

9. remove check that if KP is disabled, OM is disabled.  OM should be able to exist without KP enabled (as long as KP plugin is still installed for credentials)

10. on first requests for update order line items, check if there is an error returned

11. put retrieve Klarna order in a method

12. Slobodan to check if it is possible to stop the Woo order update if Klarna order update fails

**Comment by slobodan** [comment]
@kristibarbosky copying your notes to add to-do list, to keep track of progress.

- [ ] Revise code so that it works outside of US too; do not hard code US anywhere
along with this, the authorize doesn't need purchase_currency or locale so these settings can be removed

- [ ] for US, there should be no tax amount/rate on discounts, e.g. it should look like:

    {
      "reference": "discount",
      "type": "discount",
      "quantity": 1,
      "quantity_unit": "",
      "name": "Discount (5BUCKSOFF)",
      "total_amount": -500,
      "unit_price": -500,
      "total_discount_amount": 0,
      "tax_rate": 0,
      "total_tax_amount": 0,
      "merchant_data": null,
      "product_url": null,
      "image_url": null
    },


- [ ] remove PayPal class for "What is Klarna?" link; instead just use inline CSS

- [ ] purchase_country on order attribute - should be pulled from store info, not customer info

- [ ] clean up of create_request_url

- [ ] use a method if necessary, and use consistent way of calculating numbers, e.g. sometimes it wa number_format then round, other times 

multiply by 100 then round (applies to both KP & OM plugins)

- [ ] if no shipping method is set, can the order still be placed?   Slobodan to check. 

OM plugin:

- [ ] with the notification url, for stop requests - don't cancel orders, instead send email to merchant (if possible) and put not on order 

- [ ] remove check that if KP is disabled, OM is disabled.  OM should be able to exist without KP enabled (as long as KP plugin is still installed for credentials)

- [ ] on first requests for update order line items, check if there is an error returned

- [ ] put retrieve Klarna order in a method

- [ ] Slobodan to check if it is possible to stop the Woo order update if Klarna order update fails

**Comment by slobodan** [comment]
Checking out without a shipping method selected, WooCommerce throws this notice if you try to do it:

![screen shot 2017-03-17 at 12 29 48](https://cloud.githubusercontent.com/assets/129607/24041392/7cbf6d3c-0b0d-11e7-8326-e64c2eb13a94.png)

**Comment by slobodan** [comment]
@kristibarbosky can you send me contents for this email:

"with the notification url, for stop requests - don't cancel orders, instead send email to merchant (if possible) and put not on order"

**Comment by slobodan** [comment]
@kristibarbosky:

"Slobodan to check if it is possible to stop the Woo order update if Klarna order update fails"

When we send the update to Klarna WooCommerce order is already updated and we can't revert the changes. 

It is possible to use a different hook, before WooCommerce does its own update, althought format of data we'd have would be very different, so it's not just a matter of changing the hook we use, there's more work to it, and if we do this, if Klarna order update succeeds, but then WooCommerce order update fails, we have the same situation. 

I suggest leaving it as is, with the order note as we have it. Thoughts?

**Comment by kristibarbosky** [comment]
@slobodan 
Regarding order updates, it seems likely that the Klarna order update could fail (e.g. for valid reasons such as trying to increase order amount) but unlikely that a Woo order update will fail (since there isn't validation for Woo order changes).  Because of that, it does seem more appropriate to do the Klarna update first to best keep the 2 systems in sync.  

Given that this issue of order updates isn't a big issue currently though, why don't we do this work as a separate enhancement in the future as time permits, and separate from the other changes on this ticket.  Can that work?  But we can of course discuss further if helpful

**Comment by slobodan** [comment]
@kristibarbosky I agree. Let's leave it out of this issue, I'll create a new one instead.

**Comment by slobodan** [comment]
@kristibarbosky can you look into this please.

Currently we only send "smart coupons" as separate line items (type = discount), cart and product discounts are applied to line items directly. 

Smart coupons have no tax attached to them, it's always zero, so tax rate and tax amount are zero as well. 

Where did this one - "for US, there should be no tax amount/rate on discounts, e.g. it should look like" - come from? Was it caught in an order, or just based on looking at the code?

**Comment by kristibarbosky** [comment]
@slobodan - it was from Jason's code review.
