### ISSUE TITLE
Klarna checkout hanging on iPad / iOS safari

### ISSUE THREAD

**Issue by yratof** [krokedil/klarna-payments-for-woocommerce#61]
Tried this on several iPads on various iOS versions.

### Example website:
fjellrevenshop.no

### Steps to reproduce:

Add item to cart, head to /kasse/.

### What you'll see:

The page is unresponsive intermittently, ending in the page loading after 1.5-2 minutes, presumably when Klarna timesout

Console is saying:

`common.js:4093` Is returning `!! Maximum call stack size exceeded`
`common.js:21503` Is returning `!! Maximum call stack size exceeded`
`common.js:21521` Is returning `!! Maximum call stack size exceeded`

**Comment by yratof** [comment]
Spoke to Klarna about this issue, but they said they didn't have an iPad to test such a thing

**Comment by slobodan** [comment]
@yratof this is a Klarna Checkout issue, not Klarna Payments, correct?

**Comment by yratof** [comment]
yes, only seems to happen with the checkout

**Comment by slobodan** [comment]
Got it, thank you.

This repo is for [Klarna Payments](https://developers.klarna.com/en/no/kco-v3/klarna-payment-methods), which is a different product.

Responding here, and closing this issue because it works fine for me in my local environment, although I was able to replicate it in your site.

Can you please test in your staging environment, with all bur necessary plugins disabled, and if possible one of the default themes active, and then if the problem still exists, open another issue here:

https://github.com/krokedil/woocommerce-gateway-klarna

**Comment by yratof** [comment]
oops, yeah I clearly see that now ha, I just expected the browser to auto-fill the right domain. Following up on alt. repo now 👍
