### ISSUE TITLE
KP plugin - support for Conditional Product Fees

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#62]
Merchant is utilizing the below plugin for to calculate product fees "California Recycling Fee".  When checking out with a California address, Klarna rejects the KP order with a BAD_VALUE error due to order_total not matching the sum of the order_lines, see attached file.  

WooCommerce Conditional Product Fees for Checkout PRO 
https://wordpress.org/plugins/woo-conditional-product-fees-for-checkout/

Unless there is a better plugin to use, can KP support this plugin for conditional product fees?

[product fees BAD_VALUE.txt](https://github.com/krokedil/klarna-payments-for-woocommerce/files/1488931/product.fees.BAD_VALUE.txt)

**Comment by slobodan** [comment]
I only have access to free version of this plugin, so I can't test with exact same setup as described.

However, the issue seems to have occured due to fee being taxable, while KP plugin always had them with tax = 0.

Should be fixed now in `develop`, but please check if their fee was indeed taxable.

**Comment by kristibarbosky** [comment]
The merchant has been updated the plugin and issue is resolved.
Awaiting follow up regarding if the fee was taxable.

**Comment by NiklasHogefjord** [comment]
Closing this one. This will be worked on in https://github.com/krokedil/klarna-payments-for-woocommerce/issues/94
