### ISSUE TITLE
Include HTML for KP title in plugin code

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#7]
Currently if I enter the HTML into the Title (in Woo admin settings) to make Klarna show as desired by marketing, the HTML is also displayed (but not interpreted) in the Order details page, see attached.  The part starting with the image open tag should be moved into the plugin code to avoid this issue.

Note: there are discussions regarding legally if/how merchants should be able to control how Klarna is displayed.  For more information, see Melissa Thobe.  Klarna will be branded differently across markets though.

Pay Over Time <img src="https://cdn.klarna.com/1.0/shared/image/generic/logo/en_us/basic/black.png?width=100" alt="Klarna" />  <a style="float:right;line-height: 52px;font-size: .83em" href="https://www.klarna.com/us/pay-over-time" title="What is Klarna?">What is Klarna?</a>

![title html in payment name](https://cloud.githubusercontent.com/assets/15654455/22700128/88c68e98-ed27-11e6-9aff-4a75fbe835c5.png)

**Comment by slobodan** [comment]
There's a way to display this only on front-end. Working on it, and making it non-configurable, for now. Please review and let me know if this should be a configurable opion.

However, the float in inline CSS on `<a>` element won't work, because it will interfere with WooCommerce CSS, and I'm guessing CSS for most themes.

How about something like this:

<img width="487" alt="screen shot 2017-02-08 at 12 22 56" src="https://cloud.githubusercontent.com/assets/129607/22735293/58508a34-edf9-11e6-83b3-860881678534.png">

Title ("Klarna Payments") is configurable, everything else there (currently) is not.

Please assign the issue back to me when you respond. I use issue filters to only view the ones assigned to me, that's why I'm assigning them to you temporarily.

**Comment by slobodan** [comment]
What's also possible, and much more common for WooCommerce payment gateways is to only show the logo, and have it linked, withouth the extra text ("What is Klarna?" in this case).

Seems to look OK with the text, but it should be checked with every single theme.

**Comment by kristibarbosky** [comment]
This new window that is opened when the customer clicks the "What is Klarna" link needs to be a modal window, not take over the current window.

**Comment by slobodan** [comment]
What is it that's making it open in modal? Is there another library we need to load?

Would it be OK to keep the image where it is in my screenshot, but move "What is Klarna" link down, above or below the iframe?

**Comment by slobodan** [comment]
Open "What is Klarna?" in a new tab (for now)

**Comment by kristibarbosky** [comment]
1. UI designer requested:
Please update the Klarna payment selector to "width:68px;" (i.e. adjust the end of the url to "=68" on the HTML for Klarna Payments on the checkout page)

Also:
2. Opening the link in a new tab is fine for go live/next week, but when reasonable, he would prefer a child modal popup window instead (so that on mobile it doesn't take the customer away from the checkout page).

3. We would still also like to get the "What is Klarna" link (floated right) to work.  It seems to work fine for the "What is PayPal" link; can we use similar HTML?

onclick="javascript:window.open('https://www.klarna.com/us/pay-over-time','WIKlarna','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;"

**Comment by slobodan** [comment]
@kristibarbosky can we close this one and move the discussion to #19?

**Comment by kristibarbosky** [comment]
Unless we get further pushback, we'll plan to leave the payment selector as shown in #19
