### ISSUE TITLE
Gracefully handle customer cart in 2 separate browser windows

### ISSUE THREAD

**Issue by kristibarbosky** [krokedil/klarna-payments-for-woocommerce#8]
1. Customer gets to Woo checkout page with KP but doesn't yet place the order.
2. Open a 2nd browser tab and increase item quantities on the cart page.
3. Go back to the 1st browser tab and place the order.
4. An error is returned:  Klarna error failed. 409 - Conflict.

**Comment by slobodan** [comment]
@kristibarbosky you win testing :) I'd never think of this. Working on a solution, looks like jQuery has a way to detect switching tabs.

**Comment by slobodan** [comment]
Here's a solution that work. 

Using Page Visibility API, when a tab with checkout page becomes active, if KP is the selected option, we trigger update_checkout. 

This lets WooCommerce handle everything, rather than us doing it. Here's the error message WC displays.

<img width="1149" alt="screen shot 2017-02-08 at 15 13 49" src="https://cloud.githubusercontent.com/assets/129607/22740782/4596bd88-ee11-11e6-8319-f388f11599ff.png">

**Comment by kristibarbosky** [comment]
With klarna-payments-for-woocommerce-feature-issue-8, after updating the quantity at the cart page or adding order line items from the product page, when I return to the first tab, now the page refreshes and the new amount is reflected correctly.  I can then place the order successfully, but I don't ever get the error "Sorry, your session has expired.  Return to shop"

I think this is acceptable behavior to close the ticket, but please advise as your last comment made me think I should receive the error message.

**Comment by slobodan** [comment]
Yes, this is how WooCommerce would handle it with its built-in payment gateways as well.

**Comment by kristibarbosky** [comment]
great, closing this ticket then
